
[tool.mypy]
python_version = "3.10"
mypy_path = ""
disallow_untyped_defs = true
check_untyped_defs = true
strict_optional = true
no_implicit_optional = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

[tool.black]
skip-string-normalization = true
line-length = 120
include_trailing_comma = true

[tool.isort]
profile = "black"
line_length=120
include_trailing_comma = true
