name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
#      redis-stack:
#        image: redis/redis-stack-server:latest
#        ports:
#          - 6379:6379
#          - 8001:8001
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      env:
        DB_HOST: postgres
      run: |
        cd api_yamdb
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py test
#    - name: Test with flake8
#      run: |
#        python -m flake8 core api_client api_mediator personal_account_auth personal_account_transaction